# Generated by Django 5.0.3 on 2024-03-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.BigIntegerField(null=True),
        ),
    ]
