# Generated by Django 5.0.3 on 2024-03-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
